version: '3'

services:
  tempr_redis:
    image: "redis:alpine"
    container_name: tempr_redis
    volumes:
      - ../redis-data:/var/lib/redis
      - ../redis.conf:/usr/local/etc/redis/redis.conf

  tempr_db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=tempr
      - POSTGRES_USER=tempr
      - POSTGRES_DB=tempr
      
  tempr_app:
    image: tempr/app
    container_name: tempr_app
    ports:
      - "3000:3000"
    command: python3 manage.py runserver 0.0.0.0:3000
    volumes:
      - .:/code
    depends_on:
      - tempr_db
    environment:
      - DATABASE_URL=postgres://tempr:tempr@tempr_db/tempr

volumes:
  postgres-data:
